name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    concurrency:
      group: publish
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: npm ci && npm run build

      - name: Secret
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package on NPM
        run: npm publish --provenance --access public
